### ISSUE TITLE
can't find _http_common from /node_modules/restify/node_modules/spdy/lib/spdy

### ISSUE THREAD

**Issue by Youmoo** [mcavage/node-restify#794]
Hi . I use restify@3.0.2  and  browserify@9.0.8 .
When browserifying my app.js , it reports an error:
```
Error: Cannot find module '_http_common' from '/Users/youmoo/personal/nodejs/node-mybatis/node_modules/restify/node_modules/spdy/lib/spdy'
```

Can you help me solve this. Thank you

**Comment by yunong** [comment]
This seems like a browserify issue. I'd suggest you contact them.

**Comment by jadbaz** [comment]
I'm having the exact same issue with webpack.
Did you find a fix for this?

**Comment by ssube** [comment]
Also seeing this, under webpack. The module referenced doesn't exist, suggesting the dependency chain goes bad somewhere under restify.

**Comment by gebrits** [comment]
@ssube @Youmoo @yunong  anyone ever solved this?

**Comment by DonutEspresso** [comment]
It's not recommended, and perhaps not even possible, to browserify/webpack bundle the server entry point due to all the dependencies in restify that are nodejs specific. Modules like _http_common, _http_incoming (as required by spdy) are modules that exist only in node and cannot be shimmed for browser usage.
